### ISSUE TITLE
Issue running example script

### ISSUE THREAD

**Issue by rag315** [mit-ll/degas-core#1]
When running the example script 'RUN_DAAEncounter.m' the class 'DAAEncounterClass' runs into issue beginning at line 124.  There is reference to non-existing fields within the structure enc2Load.  Some of these appear to simply refer to the wrong name such as enc2Load.v_ftps vs enc2_Load.speed_ftps; however, starting at line 145 there is reference to value which are simply not provided.
![image](https://user-images.githubusercontent.com/72567181/107247591-0cf2a800-69f7-11eb-953f-b3bdc48cc6b0.png)
![image](https://user-images.githubusercontent.com/72567181/107247730-33b0de80-69f7-11eb-9f7e-c53faf2c0d66.png)

**Comment by aweinert-MIT** [comment]
@rag315 Are you still experiencing this bug?

**Comment by aweinert-MIT** [comment]
Closing issue due to lack of feedback and inability to replicate issue
