### ISSUE TITLE
Issue with 'RUN_NominalEncounter.m'

### ISSUE THREAD

**Issue by rag315** [mit-ll/degas-core#2]
Using MATLAB Version 2020b. All relevant toolboxes have been installed.

After running 'startup.m', I immediately ran 'RUN_NominalEncounter' and encountered a few errors. See below for the command window output.

`
>> startup_bayes
>> startup
Running DEGAS startup script...(D:\degas-core\code\startup.m)
Warning: DEGAS officially supports MATLAB R2018b.  You are using (R2020b) 
> In startup (line 21) 
Adding additional paths...
Adding ..\..\degas-daidalus\SimulinkInterface to path...
Adding ..\..\degas-pilotmodel to path...
Done!
>> RUN_NominalEncounter
Warning: Class 'NominalEncounterClass' uses an undocumented syntax to restrict property values. Use property validation syntax
instead. This warning will become an error in a future release. 
> In RUN_NominalEncounter (line 17) 
Warning: Class 'Simulation' uses an undocumented syntax to restrict property values. Use property validation syntax instead. This
warning will become an error in a future release. 
> In RUN_NominalEncounter (line 17) 
Warning: Class 'BasicSimulation' uses an undocumented syntax to restrict property values. Use property validation syntax instead.
This warning will become an error in a future release. 
> In RUN_NominalEncounter (line 17) 
Warning: Class 'BasicAircraftDynamics' uses an undocumented syntax to restrict property values. Use property validation syntax
instead. This warning will become an error in a future release. 
> In RUN_NominalEncounter (line 17) 
Index exceeds the number of array elements (2).

Error in NominalEncounterClass/setupEncounter (line 72)
            enc2Load = encounters(encNumber);

Error in RUN_NominalEncounter (line 27)
s.setupEncounter(encNum);
`

**Comment by rag315** [comment]
Additional issues were found with the other provided examples 'RUN_DAAEncounter.m' and 'RUN_Encounters_FastRestart.m'. For 'RUN_DAAEncounter', the same steps of clearing all, running startup, and then directly running the example was followed.

The Command Window output for 'RUN_DAAEncounter':
>> clear all
>> startup
Running DEGAS startup script...(D:\degas-core\code\startup.m)
Warning: DEGAS officially supports MATLAB R2018b.  You are using (R2020b) 
> In startup (line 21) 
Adding additional paths...
Adding ..\..\degas-daidalus\SimulinkInterface to path...
Adding ..\..\degas-pilotmodel to path...
Done!
>> RUN_DAAEncounter
Warning: Class 'DAAEncounterClass' uses an undocumented syntax to restrict property values. Use property validation syntax instead. This warning will become an error in
a future release. 
> In RUN_DAAEncounter (line 17) 
Warning: Class 'Simulation' uses an undocumented syntax to restrict property values. Use property validation syntax instead. This warning will become an error in a
future release. 
> In RUN_DAAEncounter (line 17) 
Warning: Class 'BasicSimulation' uses an undocumented syntax to restrict property values. Use property validation syntax instead. This warning will become an error in a
future release. 
> In RUN_DAAEncounter (line 17) 
Warning: Class 'BasicAircraftDynamics' uses an undocumented syntax to restrict property values. Use property validation syntax instead. This warning will become an error
in a future release. 
> In RUN_DAAEncounter (line 17) 
Reference to non-existent field 'a_ftpss'.
Error in DAAEncounterClass/setupEncounter (line 145)
            theSim.ac1Dynamics.a_ftpss = enc2Load.a_ftpss(1);
Error in RUN_DAAEncounter (line 35)
s.setupEncounter(encNum);


I then tried running 'RUN_Encounters_FastRestart' and received the error: 

Error using load
Unable to read file
'D:\degas-core\code\block_libraries\basic_libraries\unitTestUtilities\Encounters\unitTestEncounters.mat'.
No such file or directory.
Error in RUN_Encounters_FastRestart (line 79)
encounters = load(s.encounterFile);


I double checked the file tree, and 'unitTestEncounters.mat' was missing from the above path. However, there is a 'unitTestEncounters.mat' in D:\degas-core\code\examples\DAAEncounter . After copying the mat file to the correct location, I received this error: 

RUN_Encounters_FastRestart
Simulating encounter number 1
Nominal case
Reference to non-existent field 'a_ftpss'.
Error in DAAEncounterClass/setupEncounter (line 145)
            theSim.ac1Dynamics.a_ftpss = enc2Load.a_ftpss(1);
Error in RUN_Encounters_FastRestart (line 102)
        s.setupEncounter(ii, encounters);

**Comment by aweinert-MIT** [comment]
Please check your path and confirm the startup script is working as intended.

```
Unable to read file
'D:\degas-core\code\block_libraries\basic_libraries\unitTestUtilities\Encounters\unitTestEncounters.mat'.
```

The file [`degas-core\code\block_libraries\basic_libraries\unitTestUtilities\Encounters\unitTestEncounters.mat`](https://github.com/mit-ll/degas-core/blob/main/code/block_libraries/basic_libraries/unitTestUtilities/Encounters/unitTestEncounters.mat) does exist.

**Comment by aweinert-MIT** [comment]
I'm looking into the issues with `RUN_NominalEncounter`

**Comment by rag315** [comment]
Path and startup script appear fine. I implemented the updates made to `degas-core`, and it looks like those updates fixed `RUN_NominalEncounter`.

However, I tried running the other two examples `RUN_DAAEncounter` and `RUN_Encounters_FastRestart` and ran into a few errors.

For `RUN_DAAEncounter` , I received the following errors:

> In RUN_DAAEncounter (line 17) 
Index exceeds the number of array elements (2).

>Error in DAAEncounterClass/setupEncounter (line 122)
            enc2Load = encounters(encNumber);

>Error in RUN_DAAEncounter (line 35)
s.setupEncounter(encNum);

For `RUN_Encounters_FastRestart`, I received the following errors:

> In RUN_Encounters_FastRestart (line 78) 
Simulating encounter number 1
Nominal case
Error using BasicSimulation/runSimulinkFast (line 259)
Error in S-function 'DAAEncounter/DAA
System/DAIDALUS/DAIDALUSv201/S-Function
Wrapper/S-Function': S-Function
'sfnc_daidalus_alertingV201' does not exist

>Error in RUN_Encounters_FastRestart (line 104)
        evalc('s.runSimulinkFast(ii);');  - Show
        complete stack trace

**Comment by cserres** [comment]
For your error with RUN_Encounters_FastRestart.m, have you followed the directions to build Daidalus and create the S-Function: https://github.com/mit-ll/degas-daidalus/tree/main/SimulinkInterface? If so and you were able to build successfully, your error suggests that the S-Function is not on your Matlab path, so I would double check that the startup.m is adding it.

For your error with RUN_DAAEncounter.m, it looks like the encounter set you are trying to run might only have 2 encounters. I would suggest making sure unitTestEncounters.mat is on your path and that there are 100 encounters within it when you load it into Matlab.

**Comment by aweinert-MIT** [comment]
> For your error with RUN_Encounters_FastRestart.m, have you followed the directions to build Daidalus and create the S-Function: https://github.com/mit-ll/degas-daidalus/tree/main/SimulinkInterface? If so and you were able to build successfully, your error suggests that the S-Function is not on your Matlab path, so I would double check that the startup.m is adding it.
> 
> For your error with RUN_DAAEncounter.m, it looks like the encounter set you are trying to run might only have 2 encounters. I would suggest making sure unitTestEncounters.mat is on your path and that there are 100 encounters within it when you load it into Matlab.

I concur, the error of `'sfnc_daidalus_alertingV201' does not exist` indicates that MATLAB is not failing because the s function wasn't compiled correctly or the interface has issues. Rather matlab can't find the function when called, suggesting a path issue.

**Comment by rag315** [comment]
The s function has been compiled correctly and the issue has been fixed. Thank you for your help!
